# Google App Engine Configuration for Tiffin Admin Pro (Next.js)

runtime: nodejs20
service: super-admin-web

instance_class: F2

# Add the entrypoint for Next.js
entrypoint: npm start

env_variables:
  NODE_ENV: "production"
  PORT: "8080"
  # Add your environment variables here
  # NEXT_PUBLIC_FIREBASE_API_KEY: "YOUR_API_KEY"
  # NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "YOUR_AUTH_DOMAIN"
  # NEXT_PUBLIC_FIREBASE_PROJECT_ID: "YOUR_PROJECT_ID"
  # NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "YOUR_STORAGE_BUCKET"
  # NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "YOUR_MESSAGING_SENDER_ID"
  # NEXT_PUBLIC_FIREBASE_APP_ID: "YOUR_APP_ID"
  # COOKIE_SIGNATURE_KEY_1: "YOUR_SIGNATURE_KEY_1"
  # COOKIE_SIGNATURE_KEY_2: "YOUR_SIGNATURE_KEY_2"

# Let Next.js handle ALL routing including static files
# This allows Next.js's built-in server to handle the changing build IDs
handlers:
  - url: /.*
    script: auto
    secure: always

# Setup to ensure proper scaling
automatic_scaling:
  min_instances: 1
  max_instances: 3
  target_cpu_utilization: 0.65
  max_concurrent_requests: 80

network:
  session_affinity: true

build_env_variables:
  NEXT_TELEMETRY_DISABLED: "1"
