import React, { useState } from 'react';
import { View, Text, StyleSheet, FlatList, TouchableOpacity, ActivityIndicator } from 'react-native';
import { useTheme } from '../../store/themeStore';
import { useGetMenus, useDeleteMenu } from '../../api';
import { PlusCircle } from 'lucide-react-native';
import MenuForm from '../../components/MenuForm';

// TODO: The 'MenuItem' type should be generated by the API client.
interface MenuItem {
  id: string;
  name: string;
  description: string;
  price: number;
  category: string;
  image?: string;
}

const MenuManagementScreen = () => {
  const { theme } = useTheme();
  const { data: menus, isLoading, error, refetch } = useGetMenus();
  const [isFormVisible, setFormVisible] = useState(false);
  const [selectedMenuItem, setSelectedMenuItem] = useState<MenuItem | null>(null);
  
  const deleteMenuMutation = useDeleteMenu();

  const handleAddItem = () => {
    setSelectedMenuItem(null);
    setFormVisible(true);
  };

  const handleEditItem = (item: MenuItem) => {
    setSelectedMenuItem(item);
    setFormVisible(true);
  };
  
  const handleDeleteItem = async (id: string) => {
    await deleteMenuMutation.mutateAsync(id);
    refetch();
  };

  const handleSave = () => {
    setFormVisible(false);
    refetch();
  };

  const renderMenuItem = ({ item }: { item: MenuItem }) => (
    <View style={[styles.itemContainer, { backgroundColor: theme.colors.surface }]}>
      <View style={styles.itemDetails}>
        <Text style={[styles.itemName, { color: theme.colors.text }]}>{item.name}</Text>
        <Text style={[styles.itemDescription, { color: theme.colors.textSecondary }]}>{item.description}</Text>
        <Text style={[styles.itemPrice, { color: theme.colors.primary }]}>₹{item.price}</Text>
      </View>
      <View style={styles.itemActions}>
        <TouchableOpacity onPress={() => handleEditItem(item)} style={styles.actionButton}>
          <Text style={[styles.actionText, { color: theme.colors.primary }]}>Edit</Text>
        </TouchableOpacity>
        <TouchableOpacity onPress={() => handleDeleteItem(item.id)} style={styles.actionButton}>
          <Text style={[styles.actionText, { color: theme.colors.error }]}>Delete</Text>
        </TouchableOpacity>
      </View>
    </View>
  );

  if (isLoading) {
    return (
      <View style={[styles.container, styles.center, { backgroundColor: theme.colors.background }]}>
        <ActivityIndicator size="large" color={theme.colors.primary} />
      </View>
    );
  }

  if (error) {
    return (
      <View style={[styles.container, styles.center, { backgroundColor: theme.colors.background }]}>
        <Text style={{ color: theme.colors.error }}>Error fetching menus.</Text>
      </View>
    );
  }

  return (
    <View style={[styles.container, { backgroundColor: theme.colors.background }]}>
      <View style={styles.header}>
        <Text style={[styles.title, { color: theme.colors.text }]}>Menu Management</Text>
        <TouchableOpacity onPress={handleAddItem} style={styles.addButton}>
          <PlusCircle color={theme.colors.primary} size={28} />
        </TouchableOpacity>
      </View>
      
      <FlatList
        data={menus || []}
        renderItem={renderMenuItem}
        keyExtractor={(item) => item.id.toString()}
        ListEmptyComponent={
          <View style={styles.emptyContainer}>
            <Text style={[styles.emptyText, { color: theme.colors.textSecondary }]}>No menu items found.</Text>
            <Text style={[styles.emptySubText, { color: theme.colors.textSecondary }]}>Tap the '+' button to add your first item.</Text>
          </View>
        }
        contentContainerStyle={styles.listContent}
      />
      
      {isFormVisible && (
        <MenuForm
          isVisible={isFormVisible}
          onClose={() => setFormVisible(false)}
          menuItem={selectedMenuItem}
          onSave={handleSave}
        />
      )}
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  center: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
  },
  addButton: {
    padding: 8,
  },
  listContent: {
    padding: 20,
  },
  itemContainer: {
    flexDirection: 'row',
    padding: 15,
    marginBottom: 15,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  itemDetails: {
    flex: 1,
  },
  itemName: {
    fontSize: 18,
    fontWeight: '600',
  },
  itemDescription: {
    fontSize: 14,
    marginVertical: 4,
  },
  itemPrice: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  itemActions: {
    justifyContent: 'space-around',
  },
  actionButton: {
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  actionText: {
    fontWeight: '600',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 100,
  },
  emptyText: {
    fontSize: 18,
    fontWeight: '600',
  },
  emptySubText: {
    fontSize: 14,
    marginTop: 8,
  }
});

export default MenuManagementScreen;
