/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'UserActivityHandler': EventHandler<never, never>
    'UpdateUserProfile': ApiRouteHandler<{ firstName?: string | unknown; lastName?: string | unknown; phoneNumber?: string | unknown; profileImage?: string | unknown; email?: string | unknown }, ApiResponse<200, { _id?: string; email?: string; firstName?: string; lastName?: string; phoneNumber?: string; profileImage?: string }> | ApiResponse<400, { statusCode?: number; message?: string; error?: string }>, { topic: 'user.profile.updated'; data: never } | { topic: 'user.contact.changed'; data: never }>
    'GetUserProfile': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { _id?: string; email?: string; role?: string; firstName?: string; lastName?: string; phoneNumber?: string; profileImage?: string; isActive?: boolean }> | ApiResponse<401, { statusCode?: number; message?: string; error?: string }>, { topic: 'user.profile.viewed'; data: never } | { topic: 'user.cache.hit'; data: never } | { topic: 'user.cache.miss'; data: never }>
    'GetUserById': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { _id?: string; email?: string; role?: string; firstName?: string; lastName?: string; phoneNumber?: string; profileImage?: string; isActive?: boolean }> | ApiResponse<404, { statusCode?: number; message?: string; error?: string }>, { topic: 'user.cache.hit'; data: never } | { topic: 'user.cache.miss'; data: never }>
    'Update Center Inventory': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'center.inventory.updated'; data: never }>
    'Register Tiffin Center': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'partner.registered'; data: never }>
    'Get Centers by Location': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'Center Event Handler': EventHandler<never, never>
    'Center Analytics': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UpdateSubscription': ApiRouteHandler<{ status?: string | unknown; autoRenew?: boolean | unknown; paymentFrequency?: string | unknown; customizations?: Array<string> | unknown; endDate?: string | unknown }, ApiResponse<200, { _id?: string; customer?: string; plan?: string; status?: string; autoRenew?: boolean; endDate?: string }> | ApiResponse<404, { statusCode?: number; message?: string; error?: string }>, { topic: 'subscription.updated'; data: never } | { topic: 'subscription.status.changed'; data: never } | { topic: 'subscription.cache.invalidated'; data: never } | { topic: 'subscription.renewal.changed'; data: never }>
    'SubscriptionEventHandler': EventHandler<never, { topic: 'subscription.expiry.warning'; data: never }>
    'GetUserSubscription': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { _id?: string; customer?: string; plan?: unknown; status?: string; startDate?: string; endDate?: string; totalAmount?: number; autoRenew?: boolean }> | ApiResponse<404, { statusCode?: number; message?: string; error?: string }>, never>
    'CreateSubscription': ApiRouteHandler<{ customer: string; plan: string; startDate: string; endDate: string; autoRenew?: boolean | unknown; paymentFrequency?: string | unknown; totalAmount: number; discountAmount?: number | unknown; paymentId?: string | unknown; isPaid?: boolean | unknown; customizations?: Array<string> | unknown }, ApiResponse<201, { _id?: string; customer?: string; plan?: string; status?: string; totalAmount?: number; startDate?: string; endDate?: string }> | ApiResponse<400, { statusCode?: number; message?: string; error?: string }>, { topic: 'subscription.created'; data: never } | { topic: 'subscription.payment.required'; data: never } | { topic: 'subscription.notification.send'; data: never }>
    'Update Review': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'review.updated'; data: never }>
    'Review Event Handler': EventHandler<never, never>
    'Get Restaurant Reviews': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'Create Restaurant Review': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'review.created'; data: never }>
    'Create Menu Item Review': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'review.created'; data: never }>
    'StateAuditJob': CronHandler<{ topic: 'notification'; data: { template_id: string; email: string; template_data: Record<string, unknown> } }>
    'ProcessFoodOrder': EventHandler<{ id: string; email: string; quantity: unknown; pet_id: unknown }, { topic: 'notification'; data: { template_id: string; email: string; template_data: Record<string, unknown> } }>
    'Notification': EventHandler<{ template_id: string; email: string; template_data: Record<string, unknown> }, never>
    'ApiTrigger': ApiRouteHandler<{ pet: unknown; foodOrder?: unknown | unknown }, ApiResponse<200, { id: unknown; name: string; photoUrl: string }>, { topic: 'process-food-order'; data: { id: string; email: string; quantity: unknown; pet_id: unknown } }>
    'UpdateOrderStatus': ApiRouteHandler<{ status: string; estimatedDeliveryTime?: string | unknown }, ApiResponse<200, { statusCode?: number; message?: string; data?: unknown }> | ApiResponse<404, { statusCode?: number; message?: string; error?: string }>, { topic: 'order.status.updated'; data: never } | { topic: 'order.notification.send'; data: never } | { topic: 'order.delivered'; data: never }>
    'OrderNotificationHandler': EventHandler<never, never>
    'GetOrder': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { statusCode?: number; message?: string; data?: unknown }> | ApiResponse<404, { statusCode?: number; message?: string; error?: string }>, never>
    'CreateOrder': ApiRouteHandler<{ customer: string; businessPartner: string; items: Array<unknown>; totalAmount: number; deliveryAddress: string; deliveryInstructions?: string | unknown; scheduledDeliveryTime?: string | unknown }, ApiResponse<201, { statusCode?: number; message?: string; data?: unknown }> | ApiResponse<400, { statusCode?: number; message?: string; error?: string }>, { topic: 'order.created'; data: never } | { topic: 'order.payment.required'; data: never } | { topic: 'order.notification.send'; data: never }>
    'SendNotification': ApiRouteHandler<{ title: string; message: string; type?: string | unknown; variant?: string | unknown; category?: string | unknown; userId?: string | unknown; partnerId?: string | unknown; orderId?: string | unknown; data?: Record<string, unknown> | unknown; scheduledFor?: string | unknown; channels?: Array<string> | unknown; templateKey?: string | unknown; templateVariables?: Record<string, unknown> | unknown }, ApiResponse<201, { success?: boolean; notificationId?: string; deliveryStats?: { expo?: { sent?: number; failed?: number }; firebase?: { sent?: number; failed?: number } } }> | ApiResponse<400, { statusCode?: number; message?: string; error?: string }>, { topic: 'notification.sent'; data: never } | { topic: 'notification.delivery.success'; data: never } | { topic: 'notification.delivery.failed'; data: never }>
    'NotificationEventHandler': EventHandler<never, never>
    'UpdateMenuItem': ApiRouteHandler<{ name?: string | unknown; description?: string | unknown; price?: number | unknown; imageUrl?: string | unknown; category?: string | unknown; isAvailable?: boolean | unknown; tags?: Array<string> | unknown; allergens?: Array<string> | unknown; nutritionalInfo?: unknown | unknown }, ApiResponse<200, { _id?: string; name?: string; price?: number; businessPartner?: string }> | ApiResponse<404, { statusCode?: number; message?: string; error?: string }>, { topic: 'menu.item.updated'; data: never } | { topic: 'menu.cache.invalidated'; data: never } | { topic: 'menu.availability.changed'; data: never }>
    'MenuCacheHandler': EventHandler<never, never>
    'GetPartnerMenu': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, Array<{ _id?: string; name?: string; price?: number; isAvailable?: boolean }>> | ApiResponse<404, { statusCode?: number; message?: string; error?: string }>, never>
    'CreateMenuItem': ApiRouteHandler<{ name: string; description?: string | unknown; price: number; imageUrl?: string | unknown; businessPartner: string; category?: string | unknown; isAvailable?: boolean | unknown; tags?: Array<string> | unknown; allergens?: Array<string> | unknown; nutritionalInfo?: unknown | unknown }, ApiResponse<201, { _id?: string; name?: string; price?: number; businessPartner?: string }> | ApiResponse<400, { statusCode?: number; message?: string; error?: string }>, { topic: 'menu.item.created'; data: never } | { topic: 'menu.cache.invalidated'; data: never }>
    'EmailEventHandler': EventHandler<never, never>
    'UserLogin': ApiRouteHandler<{ email: string; password: string }, ApiResponse<200, { statusCode: unknown; message: string; data: Record<string, unknown> }> | ApiResponse<401, { statusCode?: number; message?: string; error?: string }>, { topic: 'user.authenticated'; data: never } | { topic: 'auth.login.success'; data: never } | { topic: 'auth.login.failed'; data: never }>
    'AuthSuccessHandler': EventHandler<never, never>
    'AuthFailureHandler': EventHandler<never, never>
    'GetUserAnalytics': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { userId?: string; period?: string; spending?: { total?: number; orders?: number; averageOrderValue?: number }; orders?: { completed?: number; cancelled?: number; totalOrders?: number }; preferences?: { favoritePartners?: Array<unknown>; favoriteCuisines?: Array<unknown>; popularItems?: Array<unknown> }; insights?: unknown; timestamp?: string }>, { topic: 'analytics.user.viewed'; data: never } | { topic: 'user.insights.generated'; data: never }>
    'GetPlatformAnalytics': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { period?: string; platform?: { totalRevenue?: number; totalOrders?: number; activePartners?: number; activeUsers?: number }; performance?: { systemUptime?: string; averageResponseTime?: number; cacheHitRate?: number }; trends?: unknown; timestamp?: string }>, { topic: 'analytics.platform.viewed'; data: never } | { topic: 'analytics.system.monitored'; data: never }>
    'GetPartnerAnalytics': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { partnerId?: string; period?: string; revenue?: { total?: number; orders?: number; averageOrderValue?: number }; orders?: { pending?: number; preparing?: number; delivered?: number; cancelled?: number }; popularItems?: Array<unknown>; timestamp?: string }>, { topic: 'analytics.partner.viewed'; data: never } | { topic: 'analytics.cache.hit'; data: never } | { topic: 'analytics.cache.miss'; data: never }>
    'AnalyticsEventHandler': EventHandler<never, never>
  }
}