import React, { useState } from 'react';
import { View, Text, TextInput, StyleSheet, TouchableOpacity, Modal, ScrollView, ActivityIndicator } from 'react-native';
import { useTheme } from '../store/themeStore';
import { useCreateMenu, useUpdateMenu } from '../api';
import { UploadComponent } from './ui/UploadComponent';
import { UploadType } from '../services/cloudinaryUploadService';

// TODO: The 'MenuItem' type should be generated by the API client.
interface MenuItem {
  id: string;
  name: string;
  description: string;
  price: number;
  category: string;
  image?: string;
}

interface MenuFormProps {
  isVisible: boolean;
  onClose: () => void;
  onSave: () => void;
  menuItem: MenuItem | null;
}

const MenuForm: React.FC<MenuFormProps> = ({ isVisible, onClose, menuItem, onSave }) => {
  const { theme } = useTheme();
  const [name, setName] = useState(menuItem?.name || '');
  const [description, setDescription] = useState(menuItem?.description || '');
  const [price, setPrice] = useState(menuItem?.price?.toString() || '');
  const [category, setCategory] = useState(menuItem?.category || '');
  const [files, setFiles] = useState(menuItem?.image ? [{ uri: menuItem.image, uploading: false }] : []);

  const createMenuMutation = useCreateMenu();
  const updateMenuMutation = useUpdateMenu();

  const handleSave = async () => {
    const menuItemData = {
      name,
      description,
      price: parseFloat(price),
      category,
      image: files[0]?.cloudinaryUrl || menuItem?.image,
    };

    if (menuItem) {
      await updateMenuMutation.mutateAsync({ id: menuItem.id, data: menuItemData });
    } else {
      await createMenuMutation.mutateAsync(menuItemData);
    }
    onSave();
  };
  
  const isLoading = createMenuMutation.isPending || updateMenuMutation.isPending;

  return (
    <Modal visible={isVisible} animationType="slide" onRequestClose={onClose}>
      <ScrollView style={{ flex: 1, backgroundColor: theme.colors.background }}>
        <View style={styles.container}>
          <Text style={[styles.title, { color: theme.colors.text }]}>{menuItem ? 'Edit Menu Item' : 'Add Menu Item'}</Text>
          
          <TextInput
            style={[styles.input, { backgroundColor: theme.colors.surface, color: theme.colors.text }]}
            placeholder="Item Name"
            value={name}
            onChangeText={setName}
          />
          <TextInput
            style={[styles.input, { backgroundColor: theme.colors.surface, color: theme.colors.text }]}
            placeholder="Description"
            value={description}
            onChangeText={setDescription}
            multiline
          />
          <TextInput
            style={[styles.input, { backgroundColor: theme.colors.surface, color: theme.colors.text }]}
            placeholder="Price"
            value={price}
            onChangeText={setPrice}
            keyboardType="numeric"
          />
          <TextInput
            style={[styles.input, { backgroundColor: theme.colors.surface, color: theme.colors.text }]}
            placeholder="Category"
            value={category}
            onChangeText={setCategory}
          />
          
          <UploadComponent
            title="Menu Item Image"
            uploadType={UploadType.MEAL_IMAGE}
            maxFiles={1}
            files={files}
            onFilesChange={setFiles}
          />

          <View style={styles.buttonContainer}>
            <TouchableOpacity onPress={onClose} style={[styles.button, styles.cancelButton]}>
              <Text style={styles.buttonText}>Cancel</Text>
            </TouchableOpacity>
            <TouchableOpacity onPress={handleSave} style={[styles.button, { backgroundColor: theme.colors.primary }]} disabled={isLoading}>
              {isLoading ? <ActivityIndicator color="#fff" /> : <Text style={styles.buttonText}>Save</Text>}
            </TouchableOpacity>
          </View>
        </View>
      </ScrollView>
    </Modal>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 20,
  },
  input: {
    height: 50,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    paddingHorizontal: 15,
    marginBottom: 15,
    fontSize: 16,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  button: {
    flex: 1,
    height: 50,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 5,
  },
  cancelButton: {
    backgroundColor: '#ccc',
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
});

export default MenuForm;
